### ISSUE TITLE
Support copy single step as Nightwatch script

### ISSUE THREAD

**Issue by jecfish** [nightwatchjs/nightwatch-recorder-extension#4]
Chrome 109 launches a new "Copy a single step as script" feature. 

**How to test**
- In a recording, right click on a step, select copy as [your extension] script option. 

**Action required**
- Your extension needs to implement the [stringifyStep](https://developer.chrome.com/docs/extensions/reference/devtools_recorder/#examples) API for this feature to work.
- You can test this feature with the latest Chrome Canary

<img width="1131" alt="recorder-copy" src="https://user-images.githubusercontent.com/5917927/200954152-6c1f106b-8006-4cba-9c12-1967703e917a.png">

**Comment by jecfish** [comment]
@vaibhavsingh97 FYI!

**Comment by vaibhavsingh97** [comment]
This is awesome 🙌

Raised a PR https://github.com/nightwatchjs/nightwatch-chrome-recorder/pull/8 to add support to the core package.

**Comment by jecfish** [comment]
Woo-hoo, that's quick! Thanks @vaibhavsingh97 🙌

**Comment by vaibhavsingh97** [comment]
@jecfish I had submitted to publish a new version of the extension to the chrome webstore

**Comment by vaibhavsingh97** [comment]
Chrome Extension [v0.2.0](https://chrome.google.com/webstore/detail/nightwatch-chrome-recorde/nhbccjfogdgkahamfohokdhcnemjafjk) is published
